nacos:
  config:
    server-addr: 127.0.0.1:8848 # Nacos 服务器地址
    bootstrap:
      enable: true # 是否开启 Nacos 配置预加载功能。默认为 false。
      log-enable: true # 是否开启 Nacos 支持日志级别的加载时机。默认为 false
    data-id: example # 使用的 Nacos 配置集的 dataId。
    type: yaml
    group: DEFAULT_GROUP # 使用的 Nacos 配置分组，默认为 DEFAULT_GROUP
    namespace:  # 使用的 Nacos 的命名空间，默认为 null。