spring:
  # redis
  redis:
    host: 127.0.0.1
    port: 6379
    redisson:
      # 配置单点模式
      config: classpath:redisson-single-dev.yml
swagger:
  enable: true
  title: mall子系统
  description: mall子系统
  version: 1.0.0
  base-package: cn.boot.st.redis.controller