spring:
  redis:
    port: 6379
    database:
    host: 127.0.0.1
    password: 123456
    jedis:
      pool:
        max-active: 200
        max-wait: 3000ms
        max-idle: 200
        min-idle: 10
    timeout: 5000ms
    sentinel:
      master:
      nodes:
